version: "3.8"

services:
  attendance-dev:
    image: coramdeoyouth/attendance-dev
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 5
        window: 30s
    ports:
      - "8001:8001"
    environment:
      NODE_ENV: development