version: "3.8"
services:
  redash:
    image: redash/redash:latest
    depends_on:
      - postgres
      - redis
    ports:
      - "5000:5000"
    environment:
      REDASH_WEB_WORKERS: 3
      REDASH_LOG_LEVEL: "INFO"
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: coramdeo138
  redis:
    image: redis:latest
